# Generated by Django 4.0.4 on 2022-05-15 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_remove_apiowner_issue_apiowner_numberrequestlast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contact_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
